### ISSUE TITLE
Overlapping / Duplicate of ways in Brazil

### ISSUE THREAD

**Issue by erickdeoliveiraleal** [KaartGroup/Brazil#34]
Some of yours changesets is including duplicated and overlapped ways:
Areas:

http://tools.geofabrik.de/osmi/?view=routing&lon=-44.19153&lat=-2.55030&zoom=11&overlays=unconnected_major1,unconnected_major2,unconnected_major5,duplicate_ways

http://tools.geofabrik.de/osmi/?view=routing&lon=-40.38133&lat=-20.34937&zoom=11&overlays=unconnected_major1,unconnected_major2,unconnected_major5,duplicate_ways

http://tools.geofabrik.de/osmi/?view=routing&lon=-56.09865&lat=-15.60212&zoom=11&overlays=unconnected_major1,unconnected_major2,unconnected_major5,duplicate_ways

**Comment by zlavergne** [comment]
Thank you for bringing this to our attention! We will fix these and we'll look into why they happened to try and prevent further problems.
