### ISSUE TITLE
Lack of answer and feedback from your team

### ISSUE THREAD

**Issue by naoliv** [KaartGroup/Brazil#36]
Thanks for working on Brazil, but could your team be instructed to read and answer the changeset comments, when necessary, please?
For example, https://www.openstreetmap.org/changeset/65460576

There was no answer nor the data was fixed.
There are also some other comments where no answer/feedback was received.

**Comment by garylancelot** [comment]
Hi @naoliv 

I was looking into this this morning when I saw your message here. I have gotten in touch with the team working on this project and will have them follow up with you on this issue later this evening. I messaged them about the odd classifications as well as the new geometry outside of the IBGE data that was not attributed correctly. There were certainly some mistakes made that needed to be corrected and I appreciate you pointing those out so we can address them. 

Thank you!

Gary
